---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
    component: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: eks-karpenter-cluster
      component: web
  template:
    metadata:
      labels:
        app: eks-karpenter-cluster
        component: web
    spec:
      containers:
      - name: devops-toolkit
        image: vfarcic/devops-toolkit-series
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
      nodeSelector:
        topology.kubernetes.io/zone: ap-southeast-1a
